package co.edu.uniquindio.akjevents.core.theme

import androidx.compose.ui.graphics.Color

val Terracotta = Color(0xFF9C3E26)
val Sage = Color(0xFF3D6752)
val Honey = Color(0xFFC9A84B)
val WarmBackground = Color(0xFFFFF8F5)
val WarmSurface = Color(0xFFFFFFFF)
val WarmText = Color(0xFF1E1B18)
val MutedText = Color(0xFF56423D)
val SoftBorder = Color(0xFFDDC0B9)

// Tonos de marca que usan los mockups (01_splash, 02_login...)
val BrandTerracotta = Color(0xFFD96B4F)
val BrandTerracottaLight = Color(0xFFFBECE7)
val BrandSage = Color(0xFF5F8A74)
val BrandSageLight = Color(0xFFE8F1EC)
val BrandPastelYellow = Color(0xFFF8E7A2)
val BrandOnPastelYellow = Color(0xFF55450B)
val BrandDark = Color(0xFF262220)
val BrandMuted = Color(0xFF7A726D)
val BrandBorder = Color(0xFFEFE6E1)
val BrandFieldFill = Color(0xFFFBF4F0)

// Tokens Material 3 del sistema de diseño (mockups/DESIGN.md) que no están en el colorScheme
val PrimaryFixed = Color(0xFFFFDAD2)
val PrimaryFixedDim = Color(0xFFFFB4A2)
val OnPrimaryFixed = Color(0xFF3C0700)
val SurfaceContainer = Color(0xFFF5ECE7)
val SurfaceContainerLow = Color(0xFFFBF2ED)
val OutlineColor = Color(0xFF89726C)
val SurfaceContainerHigh = Color(0xFFEFE6E2)
val SurfaceContainerHighest = Color(0xFFE9E1DC)
val OnPrimaryFixedVariant = Color(0xFF802913)
val SecondaryContainer = Color(0xFFBCEAD0)
val OnSecondaryContainer = Color(0xFF416B57)
val SecondaryFixed = Color(0xFFBFEDD3)
val OnSecondaryFixedVariant = Color(0xFF244F3C)
val TertiaryColor = Color(0xFF755B00)
val OnTertiaryContainer = Color(0xFF4F3D00)
val TertiaryFixed = Color(0xFFFFE08F)
val ErrorColor = Color(0xFFBA1A1A)
